[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions/"
  node_version = "20"

[dev]
  targetPort = 8080
  autoLaunch = false
  command = "vite --host localhost --port 8080"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/worker.js"
  [headers.values]
    Cache-Control = "max-age=0,no-cache,no-store,must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Credentials = "true"

[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/@img/**/*"]

[functions."queue-fix"]
  timeout = 26

[functions."autopost-background"]
  schedule = "*/15 * * * *"
  included_files=["functions/emails/*.liquid"]

[functions."achievements-background"]
  schedule = "0 1 * * *"
  included_files=["functions/emails/*.liquid"]

[functions."autopost-notify"]
  included_files=["functions/emails/*.liquid"]

[functions."cron"]
  included_files=["functions/emails/*.liquid"]

[functions."submission-created"]
  included_files=["functions/emails/*.liquid"]

[functions."approve"]
  included_files=["functions/emails/*.liquid"]

[functions."profile"]
  included_files=["functions/emails/*.liquid"]

[[plugins]]
  package = 'netlify-plugin-contextual-env'

[[edge_functions]]
  path = "/.well-known/atproto-did"
  function = "fedify-router"

[[edge_functions]]
  path = "/xrpc/*"
  function = "fedify-router"

