export const BikeTagDefaults = {
  appId: 'com.app.biketag',
  accessToken: '8b4e2b86a724bf3f39d6766de6e67212',
  admingEmail: 'biketag@biketag.org',
  gameName: '',
  host: 'biketag.org',
  hostKey: 'ItsABikeTagGame',
  source: 'sanity',
  logo: '/images/BikeTag.svg',
  jingle: 'media/biketag-jingle-1.mp3',
  store: 'biketag',
  manifest: {
    name: 'BikeTag',
    shortName: 'BikeTag',
    description: 'BikeTag is a photo mystery tag game played on bicycles. No login required.',
    themeColor: '#000000',
  },
  /// TODO: THIS IS BAD
  sanityImagesCDNUrl: 'https://cdn.sanity.io/images/',
  sanityBaseCDNUrl: 'https://cdn.sanity.io/images/x37ikhvs/production/',
  sanityPlayerRoleID: 'rol_pcbQ68Q9L0yn1o3O',
  sanityAmbassadorRoleID: 'rol_iET51vzIn8z6Utz0',
}

export const special = [
  'zeroth',
  'first',
  'second',
  'third',
  'fourth',
  'fifth',
  'sixth',
  'seventh',
  'eighth',
  'ninth',
  'tenth',
  'eleventh',
  'twelfth',
  'thirteenth',
  'fourteenth',
  'fifteenth',
  'sixteenth',
  'seventeenth',
  'eighteenth',
  'nineteenth',
]
export const deca = ['twent', 'thirt', 'fort', 'fift', 'sixt', 'sevent', 'eight', 'ninet']
